namespace lol_stats_master_api.Models.Interfaces
{
    public interface IChallenges
    {
        int _12AssistStreakCount { get; set; }
        int abilityUses { get; set; }
        int acesBefore15Minutes { get; set; }
        int alliedJungleMonsterKills { get; set; }
        int baronTakedowns { get; set; }
        int blastConeOppositeOpponentCount { get; set; }
        int bountyGold { get; set; }
        int buffsStolen { get; set; }
        int completeSupportQuestInTime { get; set; }
        int controlWardsPlaced { get; set; }
        float controlWardTimeCoverageInRiverOrEnemyHalf { get; set; }
        float damagePerMinute { get; set; }
        float damageTakenOnTeamPercentage { get; set; }
        int dancedWithRiftHerald { get; set; }
        int deathsByEnemyChamps { get; set; }
        int dodgeSkillShotsSmallWindow { get; set; }
        int doubleAces { get; set; }
        int dragonTakedowns { get; set; }
        float earliestBaron { get; set; }
        float earliestDragonTakedown { get; set; }
        int earlyLaningPhaseGoldExpAdvantage { get; set; }
        float effectiveHealAndShielding { get; set; }
        int elderDragonKillsWithOpposingSoul { get; set; }
        int elderDragonMultikills { get; set; }
        int enemyChampionImmobilizations { get; set; }
        int enemyJungleMonsterKills { get; set; }
        int epicMonsterKillsNearEnemyJungler { get; set; }
        int epicMonsterKillsWithin30SecondsOfSpawn { get; set; }
        int epicMonsterSteals { get; set; }
        int epicMonsterStolenWithoutSmite { get; set; }
        int fasterSupportQuestCompletion { get; set; }
        int firstTurretKilled { get; set; }
        float firstTurretKilledTime { get; set; }
        int flawlessAces { get; set; }
        int fullTeamTakedown { get; set; }
        float gameLength { get; set; }
        int getTakedownsInAllLanesEarlyJungleAsLaner { get; set; }
        float goldPerMinute { get; set; }
        int hadOpenNexus { get; set; }
        int highestChampionDamage { get; set; }
        int highestCrowdControlScore { get; set; }
        int highestWardKills { get; set; }
        int immobilizeAndKillWithAlly { get; set; }
        int initialBuffCount { get; set; }
        int initialCrabCount { get; set; }
        float jungleCsBefore10Minutes { get; set; }
        int junglerKillsEarlyJungle { get; set; }
        int junglerTakedownsNearDamagedEpicMonster { get; set; }
        float kda { get; set; }
        int killAfterHiddenWithAlly { get; set; }
        int killedChampTookFullTeamDamageSurvived { get; set; }
        int killingSprees { get; set; }
        float killParticipation { get; set; }
        int killsNearEnemyTurret { get; set; }
        int killsOnLanersEarlyJungleAsJungler { get; set; }
        int killsOnOtherLanesEarlyJungleAsLaner { get; set; }
        int killsOnRecentlyHealedByAramPack { get; set; }
        int killsUnderOwnTurret { get; set; }
        int killsWithHelpFromEpicMonster { get; set; }
        int knockEnemyIntoTeamAndKill { get; set; }
        int kTurretsDestroyedBeforePlatesFall { get; set; }
        int landSkillShotsEarlyGame { get; set; }
        int laneMinionsFirst10Minutes { get; set; }
        int laningPhaseGoldExpAdvantage { get; set; }
        int legendaryCount { get; set; }
        int lostAnInhibitor { get; set; }
        float maxCsAdvantageOnLaneOpponent { get; set; }
        int maxKillDeficit { get; set; }
        int maxLevelLeadLaneOpponent { get; set; }
        int mejaisFullStackInTime { get; set; }
        float moreEnemyJungleThanOpponent { get; set; }
        int multiKillOneSpell { get; set; }
        int multikills { get; set; }
        int multikillsAfterAggressiveFlash { get; set; }
        int multiTurretRiftHeraldCount { get; set; }
        int mythicItemUsed { get; set; }
        int outerTurretExecutesBefore10Minutes { get; set; }
        int outnumberedKills { get; set; }
        int outnumberedNexusKill { get; set; }
        int perfectDragonSoulsTaken { get; set; }
        int perfectGame { get; set; }
        int pickKillWithAlly { get; set; }
        int playedChampSelectPosition { get; set; }
        int poroExplosions { get; set; }
        int quickCleanse { get; set; }
        int quickFirstTurret { get; set; }
        int quickSoloKills { get; set; }
        int riftHeraldTakedowns { get; set; }
        int saveAllyFromDeath { get; set; }
        int scuttleCrabKills { get; set; }
        float shortestTimeToAceFromFirstTakedown { get; set; }
        int skillshotsDodged { get; set; }
        int skillshotsHit { get; set; }
        int snowballsHit { get; set; }
        int soloBaronKills { get; set; }
        int soloKills { get; set; }
        int soloTurretsLategame { get; set; }
        int stealthWardsPlaced { get; set; }
        int survivedSingleDigitHpCount { get; set; }
        int survivedThreeImmobilizesInFight { get; set; }
        int takedownOnFirstTurret { get; set; }
        int takedowns { get; set; }
        int takedownsAfterGainingLevelAdvantage { get; set; }
        int takedownsBeforeJungleMinionSpawn { get; set; }
        int takedownsFirstXMinutes { get; set; }
        int takedownsInAlcove { get; set; }
        int takedownsInEnemyFountain { get; set; }
        int teamBaronKills { get; set; }
        float teamDamagePercentage { get; set; }
        int teamElderDragonKills { get; set; }
        int teamRiftHeraldKills { get; set; }
        int teleportTakedowns { get; set; }
        int tookLargeDamageSurvived { get; set; }
        int turretPlatesTaken { get; set; }
        int turretsTakenWithRiftHerald { get; set; }
        int turretTakedowns { get; set; }
        int twentyMinionsIn3SecondsCount { get; set; }
        int twoWardsOneSweeperCount { get; set; }
        int unseenRecalls { get; set; }
        float visionScoreAdvantageLaneOpponent { get; set; }
        float visionScorePerMinute { get; set; }
        int wardsGuarded { get; set; }
        int wardTakedowns { get; set; }
        int wardTakedownsBefore20M { get; set; }
    }
}